# Tips: please make sure these dir exist before run mpd
music_directory         "/data/data-exchange/sync/private/group-yui/music/"
playlist_directory		"~/.local/state/mpd/playlists"
db_file			        "~/.local/state/mpd/mpd.db"
log_file			    "~/.local/state/mpd/mpd.log"
pid_file			    "~/.local/state/mpd/mpd.pid"
state_file			    "~/.local/state/mpd/mpdstate"
sticker_file			"~/.local/state/mpd/sticker.sql"
bind_to_address		    "localhost"
restore_paused          "yes"
auto_update	            "yes"

input {
        plugin "curl"
}

# audio_output only choose one
# for linux
audio_output {
	type		"pipewire"
	name		"Pipewire Sound Server"
}

# for macos
audio_output {
    type "osx"
    name "CoreAudio Output"
}

audio_output {
    type        "fifo"
    name        "Visulaizer feed"
    path        "/tmp/mod.fifo"
    format      "44100:16:2"
}
