# keepassxc 
# exec-once = keepassxc --minimized
exec-once = ~/.config/.common/script/comm/rclone-connect.sh

# thunderbird 
# exec-once = thunderbird

# syncthing
exec-once = syncthing --no-browser

# gpg 加解密
# exec-once = kleopatra --daemon

# xwayland scale fix
exec-once = xrdb -merge ~/.Xresources

